[package]
name = "taskbook"
version = "0.1.0"
authors = ["Jeriel Baptista Verissimo <jeriel@ciandt.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.6"
serde = "1.0.92"
serde_json = "1.0.39"
